### ISSUE TITLE
Highlight on last selected item from main menu persists

### ISSUE THREAD

**Issue by tapted** [jackhou-chromium/bitmapper#45]
There's a TODO for this, but here's a bug to go with it :)

To reproduce:

1) Select `Menu` -> `Open`
2) Select `Cancel`
3) Open Menu again

The `Open` item has a dark selection highlight

Expected: no dark highlight, and [enhancement]: a light highlight only while hovering over a menu item

**Comment by hannahbeder** [comment]
Fixed in 3142e70e4e07a3a881ca2816864c65151cf30791
