### ISSUE TITLE
Canvas resize when there is something already on the canvas

### ISSUE THREAD

**Issue by katopotato** [jackhou-chromium/bitmapper#47]
To reproduce:
1. Draw something on canvas (eg - fill with bucket tool)
2. Resize canvas to smaller size by dragging one of the edges

Canvas resizes, but what is currently on the canvas should be moved with the resize operation as well.

![screenshot from 2015-01-02 10 10 07](https://cloud.githubusercontent.com/assets/5599263/5593551/ffaaea02-9268-11e4-926e-36a9fd1c2c79.png)

**Comment by katopotato** [comment]
![screenshot from 2015-01-02 13 11 19](https://cloud.githubusercontent.com/assets/5599263/5593896/f71ba3b4-9280-11e4-8b22-b4e49770dc71.png)

**Comment by hannahbeder** [comment]
Fixed in de04fde
