### ISSUE TITLE
Using a tool on edge of canvas, causes resize on what is previously drawn on canvas

### ISSUE THREAD

**Issue by katopotato** [jackhou-chromium/bitmapper#57]
Caused by 5px border placed when detecting whether or not the canvas should be resized.

Steps to reproduce:
1) Select a tool (brush/ pencil works best)
2) Draw onto canvas center, finish drawing
3) Start drawing again from near one of the edges of the canvas
Should notice that with tool movement, what is already drawn moves also.

**Comment by hannahbeder** [comment]
Fixed in 72f2db5
