### ISSUE TITLE
Alpha blending with use of brush tool

### ISSUE THREAD

**Issue by katopotato** [jackhou-chromium/bitmapper#58]
Current implementation of the brush tool does not reflect desired alpha blending properties.

for example,
if the brush tool should brush over itself (eg- opacity == 0.5), the overlapping component should not be darker (has opacity 0.5).

**Comment by katopotato** [comment]
![screenshot from 2015-01-14 16 36 00](https://cloud.githubusercontent.com/assets/5599263/5734539/828ec046-9c0b-11e4-9c1d-17a9b3f7218c.png)

**Comment by mgiuca** [comment]
Nice, I'm very happy with the way this turned out.

Maybe we can talk about doing the same for pencil and eraser tools now.

**Comment by hannahbeder** [comment]
Fixed in 44b6d49
