### ISSUE TITLE
First stroke of brush tool is drawn with pencil tool

### ISSUE THREAD

**Issue by mgiuca** [jackhou-chromium/bitmapper#59]
Steps to reproduce:
1. Select the paintbrush tool.
2. Single-click the canvas.
3. Draw a line on the canvas.

Note that the single click is square. The line is drawn with a circular brush, but you can see a square at the point where you first clicked the mouse.

Expected behaviour: All strokes should be drawn with a circular brush.

![image](https://cloud.githubusercontent.com/assets/228433/5698888/00ccfb3a-9a6d-11e4-89a7-bd27665dcede.png)

**Comment by mgiuca** [comment]
Sara: I see this issue will be fixed in [CL 195890043](https://codereview.appspot.com/195890043/) (in PencilTool.prototype.mouseDown). It would be good to separately fix it first, rather than rolling the fix in with the new feature (have it call drawBrush on mouseDown).

**Comment by katopotato** [comment]
![screenshot from 2015-01-12 16 51 22](https://cloud.githubusercontent.com/assets/5599263/5699422/6fd4f2d6-9a7b-11e4-9032-49a0709c130e.png)

**Comment by mgiuca** [comment]
It looks like this accidentally regressed due to https://codereview.appspot.com/186620043 (which probably means we need a test for it).

Re-opening and assigning to Sara.
