### ISSUE TITLE
No Icons for test

### ISSUE THREAD

**Issue by katopotato** [jackhou-chromium/bitmapper#60]
The following error results when make run_test is run.
The problem arises as in the Makefile, icons are only copied for the release and debug builds and so, the test build has no icons. 

The solution is to also copy the icons for the test build. 
The icon set that is used is the red (debug) icons from icons/badge folder.
![screenshot from 2015-01-19 09 20 27](https://cloud.githubusercontent.com/assets/5599263/5794322/99c65ee0-9fbc-11e4-89e3-b6b65c866c37.png)

**Comment by hannahbeder** [comment]
Fixed in 3a1ec6326761b9277887642c1a05e7eff3e6763f
