### ISSUE TITLE
Resize mouse icon on canvas height and width

### ISSUE THREAD

**Issue by katopotato** [jackhou-chromium/bitmapper#79]
(in both debug and release)
The mouse icon gets set to the resize icon when is at either along the plane of canvas height or canvas width.
ie. the respective resize operation will take place if you are on the same line as the horizontal or vertical edge of the canvas, even if the mouse is outside the canvas.

for example, the canvas width = 300px, canvas height = 150px. 
If the mouse is at coordinate (300, 400) - this will still cause the horizontal resize operation to occur.

**Comment by hannahbeder** [comment]
Fixed in 9869d35
