### ISSUE TITLE
Eraser drawing is temporarily visible

### ISSUE THREAD

**Issue by mgiuca** [jackhou-chromium/bitmapper#86]
Steps to reproduce (might only be release build):

1. Flood fill.
2. Select eraser.
3. Draw with the eraser.
4. Draw with the pencil.

On Step 3, you will see a black freeform line being drawn, as if you had a pencil selected. On Step 4, the black line of the eraser disappears.

The eraser canvas is somehow being drawn onto the display canvas (but not affecting the source canvas).

**Comment by katopotato** [comment]
I think already created a bug for this:
https://github.com/jackhou-chromium/bitmapper/issues/77

See this CL:
https://codereview.appspot.com/202790043

**Comment by mgiuca** [comment]
Duplicate of #77.
